[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "public/updates"
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

[dev]
  command = "npm run dev"
  targetPort = 5180
  port = 8890
  autoLaunch = false

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/version.json"]

[[plugins]]
  package = "@netlify/plugin-emails"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/api/check-update"
  to = "/.netlify/functions/check-update"
  status = 200
